### PR TITLE
Adding jq package

### PR DESCRIPTION
**Pull request by ZaheerAhmedShaik**
Additional jq package

### CODE REVIEW

**Comment by qlikossbuild** [comment]
Hi, and thanks for contributing!

Note: If you are part of Qlik R&D, you can apply to the `open-source` team in our _internal_ GitHub organization.

Before we can handle your pull request we need you to sign our contributor license agreement.
This is a one-time process and enables you to contribute without hassle to any of the qlik-oss repositories in the future.

And it only takes a few minutes! Here are some useful links to get you started:

* [Sign the CLA](https://github.com/qlik-oss/open-source/blob/master/sign-cla.md#sign-the-cla)
* [Rationale behind the CLA](https://github.com/qlik-oss/open-source/blob/master/cla-rationale.md)
* [Qlik R&D Open Source repository](https://github.com/qlik-oss/open-source#open-source-at-qlik-rd)
* [Official Slack team](http://branch.qlik.com/slack)

Having troubles? Feel free to reach out to us either here or on Slack!

**Note:** Once the CLA is sorted, you should rebase/touch this pull request to trigger an update of this CLA status.

**Comment by hairyhenderson** [comment]
@ZaheerAhmedShaik Thanks for this!

Would you mind also adding `jq` to the `node-build`/`go-build`/`py-build` Dockerfiles? That'll also have the added benefit of triggering the CLA check again (I've approved you) 😉

**Comment by ZaheerAhmedShaik** [comment]
> @ZaheerAhmedShaik Thanks for this!
> 
> Would you mind also adding `jq` to the `node-build`/`go-build`/`py-build` Dockerfiles? That'll also have the added benefit of triggering the CLA check again (I've approved you) 😉

`node-build`, `go-build` and `py-build` Dockerfiles already have the `jq` binary installed 💪 ; 
`tiny-build` is the only missing piece 😄

**Comment by hairyhenderson** [comment]
> `node-build`, `go-build` and `py-build` Dockerfiles already have the `jq` binary installed 💪

_oops_ I had missed that 😂

Just push an amended commit and CLA should re-trigger then.

**Comment by hairyhenderson** [comment]
CI's blocked because of a CircleCI outage - https://status.circleci.com/incidents/y9tdznq3z9y9 😞

**Review by varkey — APPROVED** [review]

**Review by hairyhenderson — APPROVED** [review]

**Comment by hairyhenderson** [comment]
Thanks @ZaheerAhmedShaik!!

**Pull request merged**
